name: solana_web3
description: Dart implementation of Solana's JSON RPC API with support for common Programs.
repository: https://github.com/merigo-labs/solana-web3
issue_tracker: https://github.com/merigo-labs/solana-web3/issues/new/choose
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0
  pinenacl: ^0.5.1
  solana_borsh: ^0.0.1
    # path: ../solana_borsh
  solana_buffer: ^0.0.1
    # path: ../solana_buffer
  solana_common: ^0.1.0
    # path: ../solana_common
  solana_jsonrpc: ^0.0.1
    # path: ../solana_jsonrpc
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1